management/config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'users#show'

  resources :users do
    get :get_purchase
    get :purchase

    get :get_reserve
    get :reserve

    get :get_cancel_reservation
    get :cancel_reservation

    get :get_block_ticket
    get :block_ticket

    get :journal
    get :enter
    get :exit

    get 'tickets', on: :collection
  end
  
  # resources :tickets, only: :index
  resources :events, only: :index
  resources :sessions, only: %i[new create destroy]
end

management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

management/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum role: %i[user admin]
  enum document_type: %i[passport driver_license birth_certificate]
end

management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  before_action :require_login
end

management/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = JSON.parse(HTTParty.get("http://data:3000/events").body).map do |event|
      { 
        name: event['name'], 
        date_start: DateTime.parse(event['date_start']).to_formatted_s(:long), 
        date_end: DateTime.parse(event['date_end']).to_formatted_s(:long),
        tickets: event['tickets']
      }
    end
  end
end

management/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :new]

  def new; end

  def create
    session_params = params.permit(:login, :password)
    @user = User.find_by(login: session_params[:login])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Login is invalid!"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out!"
    redirect_to new_session_path
  end
end

management/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = 'Please try to create an account again.'
      redirect_to new_user_path
    end
  end

  def index
    pp('LOLOLLLOLO')
    user = User.find_by_id(params[:userid])
    # pp({ fio: user.fio }.to_json)
    pp(user)
    return render json: { fio: user.fio }.to_json if user

    render json: { result: "false", error: "Wrong user id"}
  end

  # возвращает домашнюю страницу пользователя
  def show;end
  
  # возвращает журнал входов/выходов посетителей
  def journal 
    res = HTTParty.get("http://terminal:3000/journal", query: journal_params)
    res.headers["x-frame-options"] = "ALLOW-FROM http://terminal:3000"

    render json: res.to_a.to_json
  end

  def enter
    response = PostService.call(
      'http://terminal:3000/enter',
      { ticket_id: params[:ticket_id], zone_type: params[:zone_type] }
    )

    render json: response.to_json
  end

  def exit
    response = PostService.call(
      'http://terminal:3000/exit',
      { ticket_id: params[:ticket_id], zone_type: params[:zone_type] }
    )

    render json: response.to_json
  end

  # возвращает все билеты пользователя по параметру user_id
  def tickets
    response = HTTParty.get("http://data:3000/tickets?user_id=#{current_user.id}")
    if response.code == 404
      @tickets = { message: response['message'], status: response.code } 
    else
      @tickets = JSON.parse(response.body).map do |ticket|
        {
          type: ticket['type'],
          start_price: ticket['start_price'],
          event: ticket['event']
        }
      end
    end
  end

  # возвращает информацию обо всех мероприятиях
  def events
    events = HTTParty.get('http://data:3000/events')
    render json: events
  end

  # возвращает информацию о юзере
  def user_info
    render json: current_user, except: :password_digest
  end

  # возвращает форму покупки билета
  def get_purchase
    render :purchase_form
  end

  def purchase
    # return json: { error: 'Must be at least 13 y/o' } if params[:age] < 13

    user_params = {
      fio: params[:fio],
      age: params[:age],
      document_number: params[:document_number],
      document_type: params[:document_type]
    }

    # Проверка на ужде существование и т.д.
    # user = UserCreateService(user_params)

    user = current_user
    render json: { error: "Wrong user params"} unless user.id

    # Осуществить проверки:
    #   На наличие такого фио по дате
    #   На наличие такого док_тип + док_нам по дате
    response = PostService.call(
      'http://data:3000/tickets/purchase',
      { reservation_id: params[:reservation_id], user_id: user.id }
    )

    session.delete(:reservation_id) unless response['err']

    # TODO: redirect
    render json: response
  end

  # возвращает форму бронирования билета
  def get_reserve
    render :reserve_form
  end

  def reserve
    response = PostService.call(
      'http://data:3000/tickets/reserve',
      { ticket_type: params[:ticket_type], event_date: params[:event_date] }
    )

    # расскоментировать при заполнении data данными
    # return redirect_to user_get_reserve_path unless response[:err]

    session[:reservation_id] = response['reservation_id'] unless response['err']
    pp(['id:', response['reservation_id']])
    redirect_to user_get_purchase_path
  end

  # возвращает форму отмены брони
  def get_cancel_reservation
    render :cancel_reservation_form
  end

  def cancel_reservation
    # response = PostService.call(
    #   'http://data:3000/tickets/cancel_reservation',
    #   { reservation_id: params[:reservation_id] }
    # )

    DeleteReservationJob.set(wait: 5.minutes).perform_later(params[:reservation_id])
    session.delete(:reservation_id) #unless response['err']

    # TODO: redirect
    #render json: response
  end

  # возвращает форму блокировки билета
  def get_block_ticket
    # if current_user.admin?
    render :block_ticket_form
    # else
    # redirect_to :back, notice: 'Access to admin only!'
    # end
  end

  def block_ticket
    # redirect_to :back, notice: 'Access to admin only!' unless current_user.admin?

    response = PostService.call(
      'http://data:3000/tickets/block_ticket',
      { ticket_id: params[:ticket_id], document_number: params[:document_number] }
    )

    # TODO: redirect
    render json: response
  end

  def block_ticket
    # redirect_to :back, notice: 'Access to admin only!' unless current_user.admin?

    response = PostService.call(
      'http://data:3000/tickets/block_ticket',
      { ticket_id: params[:ticket_id], document_number: params[:document_number] }
    )

    # TODO: redirect
    render json: response
  end

  private

  def user_params
    pp = params.require(:user).permit(:id, :fio, :age, :document_type, :document_number, :login, :password)
    pp[:document_type] = params[:user][:document_type].to_i
    pp
  end

  def journal_params
    params.permit(:user_id, :action_type, :created_at, :fio, :status, :ticket_id, :sort_by => [])
  end
end

management/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    redirect_to new_session_path unless session.include? :user_id
  end
end

management/app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class='container'>
    <h2><%= event[:name] %></h2>
    <p>Начало: <%= event[:date_start] %></p>
    <p>Конец: <%= event[:date_end] %></p>
    <% event[:tickets].each do |type, data| %>
      <p><i> <%= type %>:</i> количество - <%= data['amount'] %>, цена - <%= data['price'] %> &#8381; 
        <%= link_to user_get_reserve_path(current_user) do %>
          Забронировать
        <% end %>
      </p>
      
    <% end %>
  </div>
<% end %>

<p><%= link_to 'Назад', :back %></p>

management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Src</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

management/app/views/users/_admin_actions.html.erb
<%= link_to 'Журнал entry/exit', user_journal_path(current_user) %>

management/app/views/users/_form.html.erb
<p>Добро пожаловать, <%= current_user.login %></p>

<p>
  <strong>ФИО:</strong>
  <%= current_user.fio %>
</p>

<p>
  <strong>Возраст:</strong>
  <%= current_user.age %>
</p>

<p>
  <strong>Документ:</strong>
  <%= current_user.document_type %>
</p>

<p>
  <strong>Номер документа:</strong>
  <%= current_user.document_number %>
</p>

<%= button_to "Sign out", session_path, method: :delete %>

management/app/views/users/_user_actions.html.erb
<p><%= link_to 'Мероприятия', events_path %></p>

<p><%= link_to 'Мои билеты', tickets_users_path %></p>

management/app/views/users/block_ticket_form.html.erb
<h1>Блокировка билета</h1>

<%= form_with url: user_block_ticket_path, method: :get do |form| %>

  <p>
  <%= form.label :ticket_id, "Номер билета" %>
  <%= form.number_field  :ticket_id, min: 0, required: true %>
  </p>

  <p>
  <%= form.label :document_number, "Номер документа" %>
  <%= form.text_field :document_number, required: true %>
  </p>

  <p>
  <%= form.submit "Заблокировать" %>
  </p>

<% end%>

management/app/views/users/cancel_reservation_form.html.erb
<h1>Отмена бронирования</h1>

<%= form_with url: user_cancel_reservation_path, method: :get do |form| %>

  <p>
  <%= form.label :reservation_id, "Номер брони" %>
  <%= form.number_field  :reservation_id, value: session[:reservation_id], min: 0, required: true %>
  </p>

  <p>
  <%= form.submit "Отменить" %>
  </p>

<% end%>

management/app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for @user do |f| %>
  <p>
  <%= f.label :fio %>
  <%= f.text_field :fio%><br>
  </p>

  <p>
  <%= f.label :age %>
  <%= f.number_field :age%><br>
  </p>

  <p>
  <%= f.label :document_type %>
  <%= f.number_field :document_type%><br>
  </p>

  <p>
  <%= f.label :document_number %>
  <%= f.text_field :document_number%><br>
  </p>

  <p>
  <%= f.label :login %>
  <%= f.text_field :login%><br>
  </p>

  <p>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  </p>

  <%= f.submit "Create account" %>
<% end %>

management/app/views/users/purchase_form.html.erb
<h1>Покупка билета</h1>

<%= form_with url: user_purchase_path, method: :get do |form| %>

  <p>
  <%= form.label :reservation_id, "Номер брони" %>
  <%= form.number_field :reservation_id, value: session[:reservation_id], min: 0, required: true %>
  </p>

  <p>
  <%= form.label :fio, "ФИО" %>
  <%= form.text_field :fio, value: current_user.fio, required: true %>
  </p>

  <p>
  <%= form.label :age, "Возраст" %>
  <%= form.number_field :age, value: current_user.age, in: 13..99, step: 1, required: true %>
  </p>

  <p>
  <%= form.label :document_number, "Номер документа" %>
  <%= form.text_field :document_number, value: current_user.document_number, required: true %>
  </p>

  <p>
  <%= form.label :document_type, "Тип документа" %>
  <%= form.select :document_type, [["Пасспорт", "passport"], ["Свидетельство о рождении", "birth_certificate"], ["Права", "driver_license"]], selected: current_user.document_type , required: true %>
  </p>

  <p>
  <%= form.submit "Купить" %>
  </p>

<% end%>

management/app/views/users/reserve_form.html.erb
<h1>Бронирование билета</h1>

<%= form_with url: user_reserve_path, method: :get do |form| %>

  <p>
  <%= form.label :ticket_type_0, "Fan zone" %>
  <%= form.radio_button :ticket_type, "0", required: true %>

  <%= form.label :ticket_type_1, "VIP zone" %>
  <%= form.radio_button :ticket_type, "2" %>
  </p>

  <p>
  <%= form.label :event_date, "Дата события" %>
  <%= form.datetime_local_field :event_date, required: true %>
  </p>

  <p>
  <%= form.submit "Забронировать" %>
  </p>

<% end%>

management/app/views/users/show.html.erb
<%= render 'form' %>

<% if current_user.admin? %>
  <%= render 'admin_actions' %>
<% else %>
  <%= render 'user_actions' %>
<% end %>

management/app/views/users/tickets.html.erb
<% unless @tickets.include? :status %>
  <% @tickets.each do |ticket| %>
    <div class='container'>
      <p>Тип билета: <strong><%= ticket[:type] %></strong></p>
      <p>Цена: <%= ticket[:start_price] %></p>
      <p>Мероприятие: <%= ticket[:event]['name'] %></p>
      <p>Дата мероприятия: <%= DateTime.parse(ticket[:event]['date_start']).to_formatted_s(:long) %></p>
    </div>
  <% end %>
<% else %>
  <%= @tickets[:message] %>
<% end %>

<p><%= link_to 'Назад', :back %></p>